services:
  mysql:
    image: mysql:9.3.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ENV_ROOT_PASSWORD}
      MYSQL_USER: ${ENV_MYSQL_USER}
      MYSQL_PASSWORD: ${ENV_MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - devjoaov-db:/var/lib/mysql

volumes:
  devjoaov-db: