services:
  mysql:
    image: mysql:9.3.0
    environment:
      MYSQL_ROOT_PASSWORD: devjoaov
      MYSQL_USER: joao
      MYSQL_PASSWORD: 50021
    ports:
      - "3306:3306"
    volumes:
      - devjoaov-db:/var/lib/mysql

volumes:
  devjoaov-db: