spring:
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_service?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ENV_ROOT_USER:root}
    password: ${ENV_ROOT_PASSWORD:devjoaov}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enabled: true
logging:
  level:
    dev.joaov: debug
    net.ttddyy.dsproxy.listener: debug

server:
  servlet:
    context-path: /
  error:
    include-stacktrace: on-param
  tomcat:
    threads:
      max: 20
  port: 8090